version: "3"
services:
  wireguard:
    image: linuxserver/wireguard
    hostname: wg
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Madrid
      SERVERURL: example.com
      PEERS: "peer1,peer2"
      PEERDNS: auto
    ports:
      - "51820:51820/udp"
    volumes:
      - "./share/config:/config"
      - "/lib/modules:/lib/modules"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1

